export const FETCH_COUNTRIES_LIST = 'FETCH_COUNTRIES_LIST';
export const FETCH_COUNTRIES_LIST_SUCCESS = 'FETCH_COUNTRIES_LIST_SUCCESS';
// export const FETCH_COUNTRIES_LIST_ERROR = 'FETCH_COUNTRIES_LIST_ERROR';

export const FETCH_COUNTRY_DETAILS = 'FETCH_COUNTRY_DETAILS';
export const FETCH_COUNTRY_DETAILS_SUCCESS = 'FETCH_COUNTRY_DETAILS_SUCCESS';
// export const FETCH_COUNTRY_DETAILS_ERROR = 'FETCH_COUNTRY_DETAILS_ERROR';

export const FETCH_CHART_DATA = 'FETCH_CHART_DATA';
export const FETCH_CHART_DATA_SUCCESS = 'FETCH_CHART_DATA_SUCCESS';
// export const FETCH_CHART_DATA_ERROR = 'FETCH_CHART_DATA_ERROR';
